# Generated by Django 3.1.2 on 2020-10-15 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='quantidade_paginas',
            field=models.PositiveIntegerField(default=1, verbose_name='Quantidade de Páginas'),
        ),
    ]
