# Generated by Django 3.1.2 on 2020-10-16 01:43

from django.db import migrations
import livros.models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0003_auto_20201015_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='quantidade_paginas',
            field=livros.models.PositiveIntegerRangeField(default=1, verbose_name='Quantidade de Páginas'),
        ),
    ]
